In [1]:
import numpy as np
import torch

In [2]:
a = torch.FloatTensor([[15, 30, 35, 60], [45, 60, 80, 90], [80, 30, 130, 60]])
b = torch.FloatTensor([[20, 35, 40, 65], [50, 65, 85, 95], [85, 35, 135, 65], [40, 20, 90, 90]])

In [3]:
a

tensor([[ 15.,  30.,  35.,  60.],
        [ 45.,  60.,  80.,  90.],
        [ 80.,  30., 130.,  60.]])

In [4]:
b

tensor([[ 20.,  35.,  40.,  65.],
        [ 50.,  65.,  85.,  95.],
        [ 85.,  35., 135.,  65.],
        [ 40.,  20.,  90.,  90.]])

In [5]:
N, M = a.size(0), b.size(0)
print(f'a==>{a[:,:2].unsqueeze(1).expand(N,M,2)}')
print(f'b==>{b[:,:2].unsqueeze(0).expand(N,M,2)}')
lt = torch.max(
            a[:,:2].unsqueeze(1).expand(N,M,2),  # [N,2] -> [N,1,2] -> [N,M,2]
            b[:,:2].unsqueeze(0).expand(N,M,2),  # [M,2] -> [1,M,2] -> [N,M,2]
        )

a==>tensor([[[15., 30.],
         [15., 30.],
         [15., 30.],
         [15., 30.]],

        [[45., 60.],
         [45., 60.],
         [45., 60.],
         [45., 60.]],

        [[80., 30.],
         [80., 30.],
         [80., 30.],
         [80., 30.]]])
b==>tensor([[[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 20.]],

        [[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 20.]],

        [[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 20.]]])


In [6]:
print(f'lt: {lt.shape}  \n{lt}')

lt: torch.Size([3, 4, 2])  
tensor([[[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 30.]],

        [[45., 60.],
         [50., 65.],
         [85., 60.],
         [45., 60.]],

        [[80., 35.],
         [80., 65.],
         [85., 35.],
         [80., 30.]]])


In [7]:
rb = torch.min(
            a[:,2:].unsqueeze(1).expand(N,M,2),  # [N,2] -> [N,1,2] -> [N,M,2]
            b[:,2:].unsqueeze(0).expand(N,M,2),  # [M,2] -> [1,M,2] -> [N,M,2]
        )

In [8]:
print(f'rb: {rb.shape}  \n{rb}')

rb: torch.Size([3, 4, 2])  
tensor([[[ 35.,  60.],
         [ 35.,  60.],
         [ 35.,  60.],
         [ 35.,  60.]],

        [[ 40.,  65.],
         [ 80.,  90.],
         [ 80.,  65.],
         [ 80.,  90.]],

        [[ 40.,  60.],
         [ 85.,  60.],
         [130.,  60.],
         [ 90.,  60.]]])


In [9]:
wh = rb - lt
wh[wh<0] = 0
inter = wh[:,:,0] * wh[:,:,1]

In [10]:
print(f'wh: {wh.shape}  \n{wh}')
print(f'inter: {inter.shape}\n{inter}')

wh: torch.Size([3, 4, 2])  
tensor([[[15., 25.],
         [ 0.,  0.],
         [ 0., 25.],
         [ 0., 30.]],

        [[ 0.,  5.],
         [30., 25.],
         [ 0.,  5.],
         [35., 30.]],

        [[ 0., 25.],
         [ 5.,  0.],
         [45., 25.],
         [10., 30.]]])
inter: torch.Size([3, 4])
tensor([[ 375.,    0.,    0.,    0.],
        [   0.,  750.,    0., 1050.],
        [   0.,    0., 1125.,  300.]])


In [11]:
BS = 2
B = 2
S = 3
C = 3
t = torch.rand((BS,S,S,C+B*5))
p = torch.rand((BS,S,S,C+B*5))
print(f't: {t.shape} ==> {t}')
print(f'p: {p.shape} ==> {p}')
t[:, :, :, 4] = torch.randint(low=0,high=2,size=(BS,S,S))
t[:, :, :, 9] = torch.randint(low=0,high=2,size=(BS,S,S))
print(f't: {t.shape} ==> {t}')

t: torch.Size([2, 3, 3, 13]) ==> tensor([[[[7.7978e-01, 6.4426e-01, 3.5110e-01, 4.3198e-01, 4.9435e-01,
           4.3631e-02, 9.3567e-02, 9.4299e-01, 4.3715e-02, 7.0556e-01,
           3.6855e-01, 2.2914e-01, 5.2418e-01],
          [6.3319e-01, 1.5907e-01, 2.1287e-01, 2.1802e-01, 3.0745e-01,
           4.6236e-01, 6.7604e-01, 2.1515e-01, 2.1846e-01, 3.9510e-01,
           9.1938e-01, 1.2212e-01, 8.9025e-01],
          [6.3343e-01, 3.7939e-01, 8.4133e-01, 4.7545e-01, 3.6361e-01,
           8.3286e-01, 8.1232e-01, 1.4833e-01, 2.9619e-01, 7.1316e-03,
           2.8046e-01, 3.4709e-01, 8.6245e-01]],

         [[2.3992e-01, 2.7342e-01, 4.0052e-01, 4.7182e-01, 4.4800e-01,
           4.6089e-01, 5.7720e-01, 5.7857e-01, 6.0467e-01, 7.4585e-01,
           5.9991e-02, 6.6310e-01, 2.0497e-01],
          [4.2553e-01, 6.5432e-01, 5.8260e-01, 8.1460e-01, 4.7833e-01,
           8.3818e-01, 9.2529e-01, 7.4008e-01, 1.3786e-01, 1.4399e-02,
           4.5686e-01, 3.5274e-01, 3.7841e-01],
          [1.33

In [12]:
## 获取BatchSize
N = p.size()[0]
print(f'N={N}')
## 包含目标的mask为c>0
coo_mask = t[:,:,:,4] > 0  # (B, S, S)
## 不包含目标的mask为c=0
noo_mask = t[:,:,:,4] == 0  # (B, S, S)
print(f'coo_mask: {coo_mask.shape} --> {coo_mask}')
print(f'noo_mask: {noo_mask.shape} --> {noo_mask}')
## 将mask进行扩展，方便后续计算
coo_mask = coo_mask.unsqueeze(-1).expand_as(t)  # (B, S, S, 30)
noo_mask = noo_mask.unsqueeze(-1).expand_as(t)  # (B, S, S, 30)
print(f'coo_mask: {coo_mask.shape} ==> {coo_mask}')
print(f'noo_mask: {noo_mask.shape} ==> {noo_mask}')

N=2
coo_mask: torch.Size([2, 3, 3]) --> tensor([[[ True,  True,  True],
         [False, False, False],
         [False,  True,  True]],

        [[False,  True, False],
         [ True, False,  True],
         [False,  True, False]]])
noo_mask: torch.Size([2, 3, 3]) --> tensor([[[False, False, False],
         [ True,  True,  True],
         [ True, False, False]],

        [[ True, False,  True],
         [False,  True, False],
         [ True, False,  True]]])
coo_mask: torch.Size([2, 3, 3, 13]) ==> tensor([[[[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True],
          [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True],
          [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True]],

         [[False, False, False, False, False, False, False, False, False, False,
           False, False, False],
          [False, False, False, Fa

In [13]:
coo_pred = p[coo_mask].view(-1,B*5+C)
print(f'coo_pred: {coo_pred.shape} ==> {coo_pred}  \n####  p: {p.shape}  coo_mask: {coo_mask.shape}  p[coo_mask]: {p[coo_mask].shape}  ==>  {p[coo_mask]}')
print(f'coo_mask: {coo_mask.shape}')
box_pred = coo_pred[:,:10].contiguous().view(-1,5) #box[x1,y1,w1,h1,c1]
print(f'box_pred: {box_pred.shape} ==> {box_pred}')
class_pred = coo_pred[:,10:]                       #[x2,y2,w2,h2,c2]
print(f'class_pred: {class_pred.shape} ==> {class_pred}')

coo_pred: torch.Size([9, 13]) ==> tensor([[0.1056, 0.9061, 0.9296, 0.6817, 0.8719, 0.2833, 0.9155, 0.5667, 0.0161,
         0.0549, 0.6735, 0.2769, 0.3844],
        [0.0184, 0.4669, 0.3356, 0.6385, 0.8984, 0.7565, 0.3751, 0.6226, 0.9477,
         0.9733, 0.7848, 0.0317, 0.7323],
        [0.4598, 0.1544, 0.2180, 0.2971, 0.0438, 0.8640, 0.1491, 0.1471, 0.2197,
         0.0968, 0.5433, 0.9148, 0.6907],
        [0.7856, 0.8518, 0.5973, 0.4153, 0.8028, 0.2590, 0.9521, 0.1842, 0.2251,
         0.9990, 0.5364, 0.1768, 0.9452],
        [0.3077, 0.2454, 0.2870, 0.2141, 0.0299, 0.2964, 0.9706, 0.0749, 0.4661,
         0.8007, 0.4828, 0.6219, 0.4361],
        [0.7903, 0.1554, 0.5686, 0.4053, 0.1008, 0.7826, 0.8945, 0.9568, 0.1120,
         0.7063, 0.5755, 0.7039, 0.2134],
        [0.8458, 0.6192, 0.0385, 0.1207, 0.9584, 0.8137, 0.9626, 0.8920, 0.7837,
         0.5395, 0.0201, 0.1677, 0.9764],
        [0.1789, 0.0879, 0.9171, 0.2181, 0.1401, 0.4251, 0.7892, 0.7196, 0.2931,
         0.8292, 0.1941,

## 一维情况

In [14]:
a = torch.rand(size=(3,4))
print(f'a: {a.shape} ==>  {a}')

a: torch.Size([3, 4]) ==>  tensor([[0.0442, 0.0505, 0.7367, 0.0776],
        [0.7360, 0.0349, 0.1427, 0.7083],
        [0.2292, 0.5311, 0.9138, 0.4920]])


In [15]:
am = a[:, 0] > 0.5
print(f'am: {am.shape}  ==>  {am}')
ame = am.unsqueeze(-1).expand_as(a)
print(f'ame: {ame.shape}  ==>  {ame}')

am: torch.Size([3])  ==>  tensor([False,  True, False])
ame: torch.Size([3, 4])  ==>  tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False]])


In [16]:
sa = a[ame]
print(f'sa: {sa.shape}  ==>  {sa}')
sar = sa.view(-1, 4)
print(f'sar: {sar.shape}  ==>  {sar}')

sa: torch.Size([4])  ==>  tensor([0.7360, 0.0349, 0.1427, 0.7083])
sar: torch.Size([1, 4])  ==>  tensor([[0.7360, 0.0349, 0.1427, 0.7083]])


## 二维情况

In [17]:
a = torch.rand(size=(2,3,4))
print(f'a: {a.shape} ==>  {a}')

a: torch.Size([2, 3, 4]) ==>  tensor([[[0.9907, 0.6587, 0.9684, 0.2413],
         [0.6317, 0.4024, 0.7087, 0.3897],
         [0.2685, 0.2228, 0.9266, 0.0109]],

        [[0.6140, 0.5878, 0.2332, 0.3606],
         [0.8871, 0.2283, 0.7728, 0.0134],
         [0.9268, 0.5030, 0.4671, 0.1943]]])


In [18]:
am = a[:, :, 0] > 0.5
print(f'am: {am.shape}  ==>  {am}')
ame = am.unsqueeze(-1).expand_as(a)
print(f'ame: {ame.shape}  ==>  {ame}')

am: torch.Size([2, 3])  ==>  tensor([[ True,  True, False],
        [ True,  True,  True]])
ame: torch.Size([2, 3, 4])  ==>  tensor([[[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [False, False, False, False]],

        [[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]])


In [19]:
sa = a[ame]
print(f'sa: {sa.shape}  ==>  {sa}')
sar = sa.view(-1, 4)
print(f'sar: {sar.shape}  ==>  {sar}')

sa: torch.Size([20])  ==>  tensor([0.9907, 0.6587, 0.9684, 0.2413, 0.6317, 0.4024, 0.7087, 0.3897, 0.6140,
        0.5878, 0.2332, 0.3606, 0.8871, 0.2283, 0.7728, 0.0134, 0.9268, 0.5030,
        0.4671, 0.1943])
sar: torch.Size([5, 4])  ==>  tensor([[0.9907, 0.6587, 0.9684, 0.2413],
        [0.6317, 0.4024, 0.7087, 0.3897],
        [0.6140, 0.5878, 0.2332, 0.3606],
        [0.8871, 0.2283, 0.7728, 0.0134],
        [0.9268, 0.5030, 0.4671, 0.1943]])


## torch.nonzeros()

In [29]:
a = torch.randint(low=-3, high=3, size=(12,))
print(f'a: {a.shape}  {a}')

a: torch.Size([12])  tensor([-2, -1, -1,  1,  0, -3, -3,  0, -2, -1,  2,  0])


In [33]:
sa, sa_idx = a.sort(0, descending=True)
print(f'sa: {sa.shape}  {sa}')
print(f'sa_idx: {sa_idx.shape}  {sa_idx}')
ssa = a<0
print(f'ssa: {ssa.shape}  {ssa}')
nssa = ssa.nonzero().squeeze()
print(f'nssa: {nssa.shape}  {nssa}')

sa: torch.Size([12])  tensor([ 2,  1,  0,  0,  0, -1, -1, -1, -2, -2, -3, -3])
sa_idx: torch.Size([12])  tensor([10,  3,  4,  7, 11,  1,  2,  9,  0,  8,  5,  6])
ssa: torch.Size([12])  tensor([ True,  True,  True, False, False,  True,  True, False,  True,  True,
        False, False])
nssa: torch.Size([7])  tensor([0, 1, 2, 5, 6, 8, 9])
