In [6]:
import numpy as np
import torch

In [17]:
a = torch.FloatTensor([[15, 30, 35, 60], [45, 60, 80, 90], [80, 30, 130, 60]])
b = torch.FloatTensor([[20, 35, 40, 65], [50, 65, 85, 95], [85, 35, 135, 65], [40, 20, 90, 90]])

In [18]:
a

tensor([[ 15.,  30.,  35.,  60.],
        [ 45.,  60.,  80.,  90.],
        [ 80.,  30., 130.,  60.]])

In [19]:
b

tensor([[ 20.,  35.,  40.,  65.],
        [ 50.,  65.,  85.,  95.],
        [ 85.,  35., 135.,  65.],
        [ 40.,  20.,  90.,  90.]])

In [40]:
N, M = a.size(0), b.size(0)
print(f'a==>{a[:,:2].unsqueeze(1).expand(N,M,2)}')
print(f'b==>{b[:,:2].unsqueeze(0).expand(N,M,2)}')
lt = torch.max(
            a[:,:2].unsqueeze(1).expand(N,M,2),  # [N,2] -> [N,1,2] -> [N,M,2]
            b[:,:2].unsqueeze(0).expand(N,M,2),  # [M,2] -> [1,M,2] -> [N,M,2]
        )

a==>tensor([[[15., 30.],
         [15., 30.],
         [15., 30.],
         [15., 30.]],

        [[45., 60.],
         [45., 60.],
         [45., 60.],
         [45., 60.]],

        [[80., 30.],
         [80., 30.],
         [80., 30.],
         [80., 30.]]])
b==>tensor([[[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 20.]],

        [[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 20.]],

        [[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 20.]]])


In [29]:
print(f'lt: {lt.shape}  \n{lt}')

lt: torch.Size([3, 4, 2])  
tensor([[[20., 35.],
         [50., 65.],
         [85., 35.],
         [40., 30.]],

        [[45., 60.],
         [50., 65.],
         [85., 60.],
         [45., 60.]],

        [[80., 35.],
         [80., 65.],
         [85., 35.],
         [80., 30.]]])


In [31]:
rb = torch.min(
            a[:,2:].unsqueeze(1).expand(N,M,2),  # [N,2] -> [N,1,2] -> [N,M,2]
            b[:,2:].unsqueeze(0).expand(N,M,2),  # [M,2] -> [1,M,2] -> [N,M,2]
        )

In [33]:
print(f'rb: {rb.shape}  \n{rb}')

rb: torch.Size([3, 4, 2])  
tensor([[[ 35.,  60.],
         [ 35.,  60.],
         [ 35.,  60.],
         [ 35.,  60.]],

        [[ 40.,  65.],
         [ 80.,  90.],
         [ 80.,  65.],
         [ 80.,  90.]],

        [[ 40.,  60.],
         [ 85.,  60.],
         [130.,  60.],
         [ 90.,  60.]]])


In [35]:
wh = rb - lt
wh[wh<0] = 0
inter = wh[:,:,0] * wh[:,:,1]

In [39]:
print(f'wh: {wh.shape}  \n{wh}')
print(f'inter: {inter.shape}\n{inter}')

wh: torch.Size([3, 4, 2])  
tensor([[[15., 25.],
         [ 0.,  0.],
         [ 0., 25.],
         [ 0., 30.]],

        [[ 0.,  5.],
         [30., 25.],
         [ 0.,  5.],
         [35., 30.]],

        [[ 0., 25.],
         [ 5.,  0.],
         [45., 25.],
         [10., 30.]]])
inter: torch.Size([3, 4])
tensor([[ 375.,    0.,    0.,    0.],
        [   0.,  750.,    0., 1050.],
        [   0.,    0., 1125.,  300.]])


In [49]:
BS = 2
B = 2
S = 3
C = 3
t = torch.rand((BS,S,S,C+B*5))
p = torch.rand((BS,S,S,C+B*5))
print(f't: {t.shape} ==> {t}')
print(f'p: {p.shape} ==> {p}')
t[:, :, :, 4] = torch.randint(low=0,high=2,size=(BS,S,S))
t[:, :, :, 9] = torch.randint(low=0,high=2,size=(BS,S,S))
print(f't: {t.shape} ==> {t}')

t: torch.Size([2, 3, 3, 13]) ==> tensor([[[[0.0142, 0.6487, 0.8223, 0.0865, 0.0068, 0.7607, 0.5388, 0.8554,
           0.4692, 0.5194, 0.6740, 0.4772, 0.9846],
          [0.3054, 0.3681, 0.7621, 0.3527, 0.2314, 0.2982, 0.9511, 0.8857,
           0.3697, 0.7207, 0.1754, 0.5587, 0.2369],
          [0.7427, 0.7215, 0.1949, 0.5010, 0.8407, 0.3675, 0.1254, 0.0957,
           0.0338, 0.2282, 0.7233, 0.7697, 0.2346]],

         [[0.8093, 0.9766, 0.6986, 0.3984, 0.0211, 0.2573, 0.9001, 0.7341,
           0.3550, 0.9697, 0.5084, 0.1522, 0.7065],
          [0.2417, 0.7319, 0.8172, 0.2695, 0.9654, 0.4244, 0.3202, 0.1076,
           0.6786, 0.6310, 0.0896, 0.0902, 0.0446],
          [0.1099, 0.8060, 0.2141, 0.4848, 0.7928, 0.8498, 0.8069, 0.0230,
           0.0264, 0.8124, 0.2917, 0.3929, 0.1176]],

         [[0.2192, 0.0056, 0.9860, 0.0818, 0.3917, 0.0624, 0.1066, 0.9855,
           0.0852, 0.0169, 0.0220, 0.6070, 0.0815],
          [0.7803, 0.3832, 0.4781, 0.7438, 0.9811, 0.5569, 0.0873, 0.7547,

In [51]:
## 获取BatchSize
N = p.size()[0]
print(f'N={N}')
## 包含目标的mask为c>0
coo_mask = t[:,:,:,4] > 0  # (B, S, S)
## 不包含目标的mask为c=0
noo_mask = t[:,:,:,4] == 0  # (B, S, S)
print(f'coo_mask: {coo_mask.shape} --> {coo_mask}')
print(f'noo_mask: {noo_mask.shape} --> {noo_mask}')
## 将mask进行扩展，方便后续计算
coo_mask = coo_mask.unsqueeze(-1).expand_as(t)  # (B, S, S, 30)
noo_mask = noo_mask.unsqueeze(-1).expand_as(t)  # (B, S, S, 30)
print(f'coo_mask: {coo_mask.shape} ==> {coo_mask}')
print(f'noo_mask: {noo_mask.shape} ==> {noo_mask}')

N=2
coo_mask: torch.Size([2, 3, 3]) --> tensor([[[False, False,  True],
         [ True, False,  True],
         [False,  True,  True]],

        [[False,  True, False],
         [False,  True, False],
         [False,  True,  True]]])
noo_mask: torch.Size([2, 3, 3]) --> tensor([[[ True,  True, False],
         [False,  True, False],
         [ True, False, False]],

        [[ True, False,  True],
         [ True, False,  True],
         [ True, False, False]]])
coo_mask: torch.Size([2, 3, 3, 13]) ==> tensor([[[[False, False, False, False, False, False, False, False, False, False,
           False, False, False],
          [False, False, False, False, False, False, False, False, False, False,
           False, False, False],
          [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True]],

         [[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True],
          [False, False, False, Fa

In [70]:
coo_pred = p[coo_mask].view(-1,B*5+C)
print(f'coo_pred: {coo_pred.shape} ==> {coo_pred}  \n####  p: {p.shape}  coo_mask: {coo_mask.shape}  p[coo_mask]: {p[coo_mask].shape}  ==>  {p[coo_mask]}')
print(f'coo_mask: {coo_mask.shape}')
box_pred = coo_pred[:,:10].contiguous().view(-1,5) #box[x1,y1,w1,h1,c1]
print(f'box_pred: {box_pred.shape} ==> {box_pred}')
class_pred = coo_pred[:,10:]                       #[x2,y2,w2,h2,c2]
print(f'class_pred: {class_pred.shape} ==> {class_pred}')

coo_pred: torch.Size([9, 13]) ==> tensor([[0.3672, 0.4631, 0.7041, 0.1787, 0.5035, 0.9444, 0.8160, 0.3003, 0.7540,
         0.6553, 0.2573, 0.7247, 0.0032],
        [0.7370, 0.7721, 0.8958, 0.8983, 0.1525, 0.6504, 0.1161, 0.4367, 0.6291,
         0.4282, 0.2280, 0.5798, 0.7132],
        [0.6573, 0.9688, 0.6647, 0.2688, 0.2750, 0.7268, 0.4568, 0.5151, 0.1295,
         0.1362, 0.4274, 0.2027, 0.7619],
        [0.0678, 0.2453, 0.7064, 0.3833, 0.9930, 0.2430, 0.8534, 0.6122, 0.0255,
         0.7672, 0.2824, 0.3770, 0.7820],
        [0.2513, 0.2826, 0.7433, 0.0642, 0.7265, 0.9920, 0.8762, 0.9628, 0.2441,
         0.3941, 0.1427, 0.1253, 0.2547],
        [0.9616, 0.4397, 0.9815, 0.9536, 0.7013, 0.4250, 0.0389, 0.6209, 0.2619,
         0.0085, 0.8209, 0.0921, 0.0705],
        [0.4706, 0.1345, 0.7520, 0.4354, 0.5909, 0.7040, 0.5342, 0.6167, 0.0553,
         0.9662, 0.6157, 0.0826, 0.0487],
        [0.0695, 0.2843, 0.9876, 0.5366, 0.4788, 0.0155, 0.8700, 0.0371, 0.0648,
         0.2130, 0.3673,

## 一维情况

In [75]:
a = torch.rand(size=(3,4))
print(f'a: {a.shape} ==>  {a}')

a: torch.Size([3, 4]) ==>  tensor([[0.4874, 0.4704, 0.0943, 0.6142],
        [0.9262, 0.2904, 0.8206, 0.9108],
        [0.0666, 0.1524, 0.9666, 0.8745]])


In [77]:
am = a[:, 0] > 0.5
print(f'am: {am.shape}  ==>  {am}')
ame = am.unsqueeze(-1).expand_as(a)
print(f'ame: {ame.shape}  ==>  {ame}')

am: torch.Size([3])  ==>  tensor([False,  True, False])
ame: torch.Size([3, 4])  ==>  tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False]])


In [78]:
sa = a[ame]
print(f'sa: {sa.shape}  ==>  {sa}')
sar = sa.view(-1, 4)
print(f'sar: {sar.shape}  ==>  {sar}')

sa: torch.Size([4])  ==>  tensor([0.9262, 0.2904, 0.8206, 0.9108])
sar: torch.Size([1, 4])  ==>  tensor([[0.9262, 0.2904, 0.8206, 0.9108]])


## 二维情况

In [85]:
a = torch.rand(size=(2,3,4))
print(f'a: {a.shape} ==>  {a}')

a: torch.Size([2, 3, 4]) ==>  tensor([[[0.0283, 0.6794, 0.1640, 0.2961],
         [0.1834, 0.4585, 0.5372, 0.8837],
         [0.9593, 0.3831, 0.8692, 0.8887]],

        [[0.5519, 0.9316, 0.1601, 0.2625],
         [0.6175, 0.0365, 0.3261, 0.4983],
         [0.8104, 0.8406, 0.7025, 0.5610]]])


In [86]:
am = a[:, :, 0] > 0.5
print(f'am: {am.shape}  ==>  {am}')
ame = am.unsqueeze(-1).expand_as(a)
print(f'ame: {ame.shape}  ==>  {ame}')

am: torch.Size([2, 3])  ==>  tensor([[False, False,  True],
        [ True,  True,  True]])
ame: torch.Size([2, 3, 4])  ==>  tensor([[[False, False, False, False],
         [False, False, False, False],
         [ True,  True,  True,  True]],

        [[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]])


In [87]:
sa = a[ame]
print(f'sa: {sa.shape}  ==>  {sa}')
sar = sa.view(-1, 4)
print(f'sar: {sar.shape}  ==>  {sar}')

sa: torch.Size([16])  ==>  tensor([0.9593, 0.3831, 0.8692, 0.8887, 0.5519, 0.9316, 0.1601, 0.2625, 0.6175,
        0.0365, 0.3261, 0.4983, 0.8104, 0.8406, 0.7025, 0.5610])
sar: torch.Size([4, 4])  ==>  tensor([[0.9593, 0.3831, 0.8692, 0.8887],
        [0.5519, 0.9316, 0.1601, 0.2625],
        [0.6175, 0.0365, 0.3261, 0.4983],
        [0.8104, 0.8406, 0.7025, 0.5610]])
